//
//  MovieData.swift
//  Bishop_Movies
//
//  Created by Bishop,Mackenzie N on 11/30/22.
//

import Foundation
import UIKit

//Movie struct
struct Movie{
    let title:String
    let image:UIImage
    let releasedYear:String
    let movieRating:String
    let boxOffice:String
    let moviePlot:String
    let cast:[String]
}

//Genre struct
struct Genre{
    let category:String
    let movies:[Movie] = [
        Movie(title: "After The Thin Man", image: UIImage(named: "after_the_thin_man")!, releasedYear: "1936", movieRating: "7.6", boxOffice: "$3.156 M", moviePlot: "Recently returned home from vacation, private detective Nick Charles and his socialite wife, Nora, are back on the case when Nora's cousin, Selma, reports her husband Robert missing. As the duo search for the disreputable Robert, Selma's friend David Graham, who secretly pines for her, aids the investigation. When the three begin to unravel Robert's secret life, the missing persons case turns into one of murder.", cast: ["William Powell", "Myrna Loy", "James Stewart"]),
        Movie(title: "Clue", image: UIImage(named: "clue")!, releasedYear: "1985", movieRating: "7.2", boxOffice: "$15 M", moviePlot: "Six blackmail victims are invited to an isolated mansion by a man who knows a dark secret from each of their pasts. On arrival, each is given a pseudonym drawn from Cluedo before being introduced to the blackmailer. Each is handed a weapon, at which point the lights are switched off and the blackmailer is killed. Can the guests uncover the murderer before they all become victims?", cast: ["Tim Curry", "Madeline Kahn", "Lesley Ann Warren"]),
        Movie(title: "Clueless", image: UIImage(named: "clueless")!, releasedYear: "1995", movieRating: "6.9", boxOffice: "$56.6 M", moviePlot: "Shallow, rich and socially successful Cher is at the top of her Beverly Hills high school's pecking scale. Seeing herself as a matchmaker, Cher first coaxes two teachers into dating each other. Emboldened by her success, she decides to give hopelessly klutzy new student Tai a makeover. When Tai becomes more popular than she is, Cher realizes that her disapproving ex-stepbrother was right about how misguided she was -- and falls for him.", cast: ["Alicia Silverstone", "Paul Rudd", "Brittany Murphy"]),
        Movie(title: "Die Hard", image: UIImage(named: "die_hard")!, releasedYear: "1988", movieRating: "8.2", boxOffice: "$141.5 M", moviePlot: "New York City policeman John McClane is visiting his estranged wife and two daughters on Christmas Eve. He joins her at a holiday party in the headquarters of the Japanese-owned business she works for. But the festivities are interrupted by a group of terrorists who take over the exclusive high-rise, and everyone in it. Very soon McClane realizes that there's no one to save the hostages -- but him.", cast: ["Bruce Willis", "Alan Rickman", "Bonnie Bedelia"]),
        Movie(title: "Knives Out", image: UIImage(named: "knives_out")!, releasedYear: "2019", movieRating: "7.9", boxOffice: "$312.9 M", moviePlot: "The circumstances surrounding the death of crime novelist Harlan Thrombey are mysterious, but there's one thing that renowned Detective Benoit Blanc knows for sure -- everyone in the wildly dysfunctional Thrombey family is a suspect. Now, Blanc must sift through a web of lies and red herrings to uncover the truth.", cast: ["Ana de Armas", "Daniel Craig", "Chris Evans"]),
        Movie(title: "Murder On The Orient Express", image: UIImage(named: "murder_on_the_orient_express")!, releasedYear: "1974", movieRating: "7.3", boxOffice: "$35.7 M", moviePlot: "Having concluded a case, detective Hercule Poirot settles into what he expects will be a relaxing journey home aboard the Orient Express. But when an unpopular billionaire is murdered en route, Poirot takes up the case, and everyone on board the famous train is a suspect. Using an avalanche blocking the tracks to his advantage, Poirot gradually realizes that many of the passengers have revenge as a motive, and he begins to home in on the culprit.", cast: ["Albert Finney", "Ingrid Bergman", "Lauren Bacall"]),
        Movie(title: "Notting Hill", image: UIImage(named:"notting_hill")!, releasedYear: "1999", movieRating: "7.2", boxOffice: "$363.8 M", moviePlot: "William Thacker is a London bookstore owner whose humdrum existence is thrown into romantic turmoil when famous American actress Anna Scott appears in his shop. A chance encounter over spilled orange juice leads to a kiss that blossoms into a full-blown affair. As the average bloke and glamorous movie star draw closer and closer together, they struggle to reconcile their radically different lifestyles in the name of love.", cast: ["Julia Roberts", "Hugh Grant", "Rhys Ifans"]),
        Movie(title: "Terminator 2: Judgement Day", image: UIImage(named: "terminator_2")!, releasedYear: "1991", movieRating: "8.6", boxOffice: "$520.9 M", moviePlot: "In this sequel set eleven years after The Terminator, young John Connor, the key to civilization's victory over a future robot uprising, is the target of the shape-shifting T-1000, a Terminator sent from the future to kill him. Another Terminator, the revamped T-800, has been sent back to protect the boy. As John and his mother go on the run with the T-800, the boy forms an unexpected bond with the robot.", cast: ["Edward Furlong", "Linda Hamilton", "Arnold Schwarzenegger"]),
        Movie(title: "The Dark Knight", image: UIImage(named: "the_dark_knight")!, releasedYear: "2008", movieRating: "9.0", boxOffice: "$1.006 B", moviePlot: "With the help of allies Lt. Jim Gordon and DA Harvey Dent, Batman has been able to keep a tight lid on crime in Gotham City. But when a vile young criminal calling himself the Joker suddenly throws the town into chaos, the caped Crusader begins to tread a fine line between heroism and vigilantism.", cast: ["Christian Bale", "Heath Ledger", "Morgan Freeman"]),
        Movie(title: "The Long Goodbye", image: UIImage(named: "the_long_goodbye")!, releasedYear: "1973", movieRating: "7.5", boxOffice: "$959 K", moviePlot: "Private detective Philip Marlowe is asked by his old buddy Terry Lennox for a ride to Mexico. He obliges, and when he gets back to Los Angeles is questioned by police about the death of Terry's wife. Marlowe remains a suspect until it's reported that Terry has committed suicide in Mexico. Marlowe doesn't buy it but takes a new case from a beautiful blond, Eileen Wade, who coincidentally has a past with Terry.", cast: ["Elliot Gould"]),
        Movie(title: "The Lord of the Rings: The Return of the King", image: UIImage(named: "the_lord_of_the_rings")!, releasedYear: "2003", movieRating: "9.0", boxOffice: "$1.146 B", moviePlot: "The culmination of nearly 10 years' work and conclusion to Peter Jackson's epic trilogy based on the timeless J.R.R. Tolkien classic, The Lord of the Rings: The Return of the King presents the final confrontation between the forces of good and evil fighting for control of the future of Middle-earth. Hobbits Frodo and Sam reach Mordor in their quest to destroy the `one ring', while Aragorn leads the forces of good against Sauron's evil army at the stone city of Minas Tirith.", cast: ["Elijah Wood", "Karl Urban", "Sean Astin"]),
        Movie(title: "The Matrix", image: UIImage(named: "the_matrix")!, releasedYear: "1999", movieRating: "8.7", boxOffice: "$467.2 M", moviePlot: "Neo believes that Morpheus, an elusive figure considered to be the most dangerous man alive, can answer his question -- What is the Matrix? Neo is contacted by Trinity, a beautiful stranger who leads him into an underworld where he meets Morpheus. They fight a brutal battle for their lives against a cadre of viciously intelligent secret agents. It is a truth that could cost Neo something more precious than his life.", cast: ["Keanu Reeves", "Carrie-Anne Moss", "Laurence Fishburne"]),
        Movie(title: "The Princess Bride", image: UIImage(named: "the_princess_bride")!, releasedYear: "1987", movieRating: "8.0", boxOffice: "$30.9 M", moviePlot: "A fairy tale adventure about a beautiful young woman and her one true love. He must find her after a long separation and save her. They must battle the evils of the mythical kingdom of Florin to be reunited with each other. Based on the William Goldman novel The Princess Bride which earned its own loyal audience.", cast: ["Cary Elwes", "Robin Wright", "Billy Crystal"]),
        Movie(title: "When Harry Met Sally", image: UIImage(named: "when_harry_met_sally")!, releasedYear: "1989", movieRating: "7.7", boxOffice: "$92.8 M", moviePlot: "In 1977, college graduates Harry Burns and Sally Albright share a contentious car ride from Chicago to New York, during which they argue about whether men and women can ever truly be strictly platonic friends. Ten years later, Harry and Sally meet again at a bookstore, and in the company of their respective best friends, Jess and Marie, attempt to stay friends without sex becoming an issue between them.", cast: ["Meg Ryan", "Billy Crystal", "Carrie Fisher"]),
        Movie(title: "You've Got Mail", image: UIImage(named: "you've_got_mail")!, releasedYear: "1998", movieRating: "6.7", boxOffice: "$ 250.8 M", moviePlot: "Struggling boutique bookseller Kathleen Kelly hates Joe Fox, the owner of a corporate Foxbooks chain store that just moved in across the street. When they meet online, however, they begin an intense and anonymous Internet romance, oblivious of each other's true identity. Eventually Joe learns that the enchanting woman he's involved with is actually his business rival. He must now struggle to reconcile his real-life dislike for her with the cyber love he's come to feel.", cast: ["Meg Ryan", "Tom Hanks", "Greg Kinnear"])
    ]
}
